### ISSUE TITLE
Cannot unbox header || body

### ISSUE THREAD

**Issue by seb-m** [trevp/noise#14]
Since `header` is encrypted with some randomized padding in `noiseBox()` its length is not fixed anymore, therefore when the `noiseBox()` result is opened for decryption there is no way to find the separation between the two concatenated `noiseBlob`: `header || body`.

**Comment by centromere** [comment]
The header always contains only sender_key.pub which is of constant length for any given ciphersuite. Assuming that the ciphersuite and pad lengths are known ahead of time, you can deduce the size of the header Blob as being (suite_pubkey_len + pad_len + 4 + MAC_LEN). The body would just be everything after that.

However, I'm not sure if having the pad lengths known ahead of time is a good idea. I think it might be of value to be able to randomize the pad lengths in every protocol message to prevent censorship systems from using statistical correlation on the length of the messages.
