### ISSUE TITLE
Noise imposes a (problematic) pre-sort on auth tag size

### ISSUE THREAD

**Issue by eternaleye** [trevp/noise#19]
The current Noise draft mandates auth tags of exactly 128 bits, but unlike other such constraints (such as the 256-bit key size) offers no justification. In addition, this seems to assume AEADs all work like ChaCha20-Poly1305 or AES-GCM, where the size of the auth tag is fixed.

However, there also exist AEADs such as AEZ, which has an arbitrary authentication tag length. This would be especially useful for length-hiding purposes, as rather than using some padding scheme (which is, historically speaking, a risky proposition), one could simply use the extra space for a long auth tag.

A 128-bit _minimum_, however, would seem sensible to me.

**Comment by trevp** [comment]
Added rationale.
