### ISSUE TITLE
OAE2 online-AEAD security definition may be of interest

### ISSUE THREAD

**Issue by eternaleye** [trevp/noise#20]
Rogaway et. al. published a paper on shortcomings of existing online-AEAD security notions, along with defining OAE2, which tries to resolve them. They also provide constructions for achieving OAE2 using either the CHAIN construction over (Rogaway's terminology) "Robust" or "nonce-misuse resistant" AE (AEZ, SIV), or STREAM which can use more standard nonce-based AE (ChaCha20-Poly1305, AES-GCM)

Paper: https://eprint.iacr.org/2015/189

**Comment by eternaleye** [comment]
Er, any comments? Specifically, STREAM is close to (but not the same as) the behavior described in CipherState and SymmetricState, and I was wondering if bringing them closer together might be beneficial due to stronger guarantees about the properties of the construction.

**Comment by trevp** [comment]
Dunno.  Do you have a concrete suggestion?

**Comment by eternaleye** [comment]
Well, the only difference visible in terms of behavior (aside from wire format) is that STREAM doesn't specify a `Split()` operation. However, since the Noise `Split()` rekeys both sides, it preserves security properties.

Honestly, I'd just use STREAM _as_ the bulk transport mode. It's close enough to be a relatively minor change, and gets a very nice reduction to the underlying cipher for free.

**Comment by trevp** [comment]
Could you explain, concretely, what change(s) you're asking for?

**Comment by eternaleye** [comment]
That the actual wire format of a Noise symmetric-encrypted stream be STREAM from the paper, really.

There are a couple ways to do that:

- one is pretty simple (just feeding the data from the existing API in as described in the paper, and relying on the caller to do the nonce formatting)
- another requires slight API changes (CipherState is around STREAM rather than the underlying nonce-based AE; takes a nonce at _initialization_ rather than each message)
- and another that's a bit more invasive (`Split()` uses new "stream nonces" rather than a full rekey).

**Comment by trevp** [comment]
Can you explain what you're asking for in simple terms, without reference to the paper?

**Comment by eternaleye** [comment]
Let `E_k(nonce, ad, message) -> ciphertext` be a nonce-based AEAD parameterized by the key `k`.
Then, let `SE_k(stream_nonce, Sequence<(ad, message)>) -> Sequence<ciphertext>` be a **streaming** nonce-based AEAD parameterized by `k`, with the definition:

```
for (let msg = 0; msg < messages.len(); ++msg )
    if ( is_last_message ) {
        yield E_k(stream_nonce || (msg+1) || 1, ad, messages[msg]);
    } else {
        yield E_k(stream_nonce ||  (msg+1) || 0, ad, messages[msg]);
   }
}
```

I just realized that I'd mistakenly attributed `EncryptAndIncrement` to `SymmetricState` when writing the above; please consider the `SymmetricState` in option 1 as if I had said `CipherState` and ignore option 2.

In my first suggestion, this is encapsulated almost entirely within `EncryptAndIncrement` on `CipherState` - aside from adding either a "finalize" operation (send empty-string message marked "last" with nonce pattern) or a flag on the last message, everything else is just a matter of how `EncryptAndIncrement` marshals data down to `ENCRYPT`. `Split()` still works as specified in noise.md.

In my third suggestion, which builds on the above, `Split()` can simply be implemented by initializing two new `CipherState`s with unused `stream_nonce`s. This could be done by bisecting the nonce space (simple, local, but limits max number of splits to the number of bits in the `stream_nonce`) or by using a shared counter per key, and simply allocating the next one (simple, can split effectively infinitely with sensible stream nonce sizes, but non-local - may require synchronization).

**Comment by trevp** [comment]
OK, so this seems equivalent to Noise except for the stream_nonce (which we don't need), and explicitly marking the final message.  I decided to not mark the final message based on some earlier discussions with Tiffany.  Most protocols already have a way of indicating termination, so replicating this in the crypto layer is redundant and confusing (e.g. TLS close_notify).  The "Application Responsibilities" and "Security Considerations" talk more about this.

If you want to discuss this in more depth, I'd recommend the mailing list:

https://moderncrypto.org/mail-archive/noise/2015/

**Comment by eternaleye** [comment]
Well, there's "equivalent" and there's "see this paper for a security reduction of this exact construction" - and the ability to split without the overhead of rekeying is notable.

**Comment by trevp** [comment]
I like the rekeying for Split(), it makes other parts of the security analysis easier, and is simpler than your alternatives.

If the construction is just using a unique, incrementing, nonce per message, than we already do that.  We don't tag the final message, but that's by design.

So I'm not seeing any worthwhile changes here.

**Comment by eternaleye** [comment]
Out of curiosity, how does it make the rest of the security analysis easier? After all, using STREAM means you inherit their reduction, which includes that the streams are cryptographically independent if the underlying nonce-based AEAD is sane.

And the reduction still works with `stream_nonce` having zero bits (as long as only one stream exists per key), it does make use of distinguishing the last message. I won't be confident the result holds without it until such a reduction is formulated.

**Comment by trevp** [comment]
On Wed, Nov 11, 2015 at 4:45 PM, eternaleye <notifications@github.com>
wrote:

> Out of curiosity, how does it make the rest of the security analysis
> easier? After all, using STREAM means you inherit their reduction, which
> includes that the streams are cryptographically independent if the
> underlying nonce-based AEAD is sane.
>
Key agreement protocols are often modeled within a Bellare-Rogaway
framework, where the attacker is challenged to distinguish a "session key"
from random.  If the session key is used in processing the last handshake
message, then there's a trivial distinguisher (attempt to decrypt the last
handshake message) - the people analyzing TLS complained about this a lot.

So it simplifies analysis if independent keys are derived post-handshake,
because then the attacker can be challenged to distinguish those keys.


> And the reduction still works with stream_nonce having zero bits (as long
> as only one stream exists per key), it does make use of distinguishing the
> last message. I won't be confident the result holds without it until such a
> reduction is formulated.
>
I'm not concerned about that, but feel free to bring it to the mailing list.

Trevor
