### ISSUE TITLE
Use of HASH for sensitive and non-sensitive data

### ISSUE THREAD

**Issue by stouset** [trevp/noise#21]
I'm writing an implementation in Rust that uses [libsodium's memory allocator](http://doc.libsodium.org/helpers/memory_management.html) to prevent sensitive data from being leaked. In most cases, this is straightforward to implement with Noise: `GetKey(k, n)` for example accepts a key that resides in protected memory, a nonce, and returns another key in protected memory.

`HASH(data)` is (so far as I have found) the exception to this. The input and output are both *sometimes* sensitive data (when called via `MixKey` when `has_key == False`).

It would cost an extra hash operation to replace this one case with `HMAC-HASH(data, "")`. In my case, the benefit is that I don't have to either implement `HASH` using a slower approach that uses protected memory (not just for the input and output, but also for the hash state itself).

**Comment by trevp** [comment]
Hi Stephen, I'm thinking on this, you want to put design Qs like this on the mailing list, though?

**Comment by stouset** [comment]
Sure thing, sorry about that. :)
