### ISSUE TITLE
Question: Is XX pattern vulnerable to MITM?

### ISSUE THREAD

**Issue by oblique** [trevp/noise#48]
I don't know much about cryptography, however to my understanding, the XX pattern is vulnerable to MITM.

```
  Alice                   Eve                        Bob
            e                          e'
         ------->                   ------->

       e, ee, s, es              e', ee', s', es'
         <-------                   <-------

          s, se                      s', se'
         ------->                   ------->

         messageA (reencrypted)     messageA
         <-------                   <-------

         messageB                   messageB (reencrypted)
         ------->                   ------->
```

Is this correct? Should I use XXpsk3 in order to avoid this?

**Comment by mimoo** [comment]
when using patterns like XX you want to also communicate a signature of the key by some authority that you trust (a public-key infrastructure type of deal) or make sure that the exchange was not intercepted by verifying a hash of the transcript (`h`) at the end of the key exchange. Perhaps the spec could use some words on that, I'm also not sure if there's an API to get the hash of the transcript at the end so it's probably implementation-dependent.

**Comment by oblique** [comment]
I understand, thanks!
